version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8761:8761'
    expose:
      - '8761'
    networks:
      - ms_networks
      

networks:
  ms_networks:
    #external: true
    driver: bridge
    name: ms_networks


