# main project docker-compose.yml

version: '3.8'

services:
  eureka-server:
    container_name: eureka-server
    build: 
      context: ./eureka-server   
      dockerfile: Dockerfile 
    ports:
      - '8761:8761'
    networks:
      - ms_networks
    volumes: 
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'       

  student-ms:
    container_name: student-ms
    build: 
      context: ./studentms   
      dockerfile: Dockerfile 
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    ports:
      - '8091:8091'
    networks:
          - ms_networks
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'



networks:
  ms_networks:
    #external: true
    name: ms_networks
    driver: bridge


