server:
  port: 8989

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: registration-service
          uri: lb://REGISTRATION-SERVICE
          predicates:
            - Path=/registration/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost