server:
  port: 8092

spring:
  #  h2:
  #    console:
  #      enabled: true

  application:
    name: STUDENTMS-CLIENT

#  datasource:
#    url: jdbc:h2:mem:feedb;DB_CLOSE_DELAY=-1
#    username: sa
#    password: password
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: false
#    hibernate:
#      ddl-auto: create-drop

  sql:
    init:
      platform: h2

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  instance:
#    hostname: localhost
